# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=file]
        types_or: [c++, c]
      - id: clang-tidy
        args: [--config-file=.clang-tidy, -p=.]
        types_or: [c++, c]
        # Exclude external libraries and design pattern examples
        exclude: ^(lib/|tests/design_pattern/|src/design_pattern/)
